### ISSUE TITLE
hydra-head should have tests confirming diff types of fixture objects are put in Solr properly 

### ISSUE THREAD

**Issue by jcoyne** [samvera/hydra-head#33]
Formerly HYDRA-521

These will also serve as model tests for hydra applications creating their own OM / Solrizer / Solrizer-Fedora configurations.

**Comment by terrellt** [comment]
So we've gone two years without this. Should we close this? @ndushay @jcoyne

**Comment by jcoyne** [comment]
I'm for closing it.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by jrgriffiniii** [comment]
Greater than 10 years old, closing.
