### ISSUE TITLE
Solr schema should support DocValues

### ISSUE THREAD

**Issue by atz** [samvera/hydra-head#395]
This is yet another dimension of the sprawling matrix of attributes responsible for defining dynamic namespaces, but it is important.  [DocValues](https://cwiki.apache.org/confluence/display/solr/DocValues) enables the use of Streaming Expressions via the `/stream` handler.  

The good news is it only affects `StrField`, `UUIDField`, `Trie*` numeric/date fields, and `BoolField`.  The bad news is that I don't think our strategy of enumeration is sustainable as other attributes (and attributes with wider range of values) proliferate.

**Comment by atz** [comment]
YO, basic design scalability issue!  Maybe worth a thought!

**Comment by jcoyne** [comment]
@atz it sounds like you understand this better than anyone. Can you submit a PR?

**Comment by cjcolvar** [comment]
Replaced with https://github.com/samvera/active_fedora/issues/1305 since the solr config was removed in favor of the config generated by active-fedora.
