### ISSUE TITLE
Solr schema should support DateRangeField

### ISSUE THREAD

**Issue by atz** [samvera/hydra-head#417]
See: https://lucidworks.com/2016/02/13/solrs-daterangefield-perform/

**Comment by jcoyne** [comment]
@atz What's the use case that would benefit by using a DateRangeField?

**Comment by atz** [comment]
I don't think any argument has to be made that Hydra's schema should include as many solr field types as possible, but the reasons for this one are particularly compelling.

Firstly, the article above points out that the new field performs better for standard queries than the old one: `DateRangeField out-performed both TrieDate and DocValues in general.`  So basically every use case would benefit. 

But more specifically, lease/Embargo logic, amongst any other representations of actual date ranges (life of author, years of publication, etc.).  The main value would be that we can use newer query syntax like INTERSECTS or CONTAINS with the date range that are not possible w/ any number of regular date fields or date field values.  E.g.:
```
q={!field f=dateRange op=Contains v="[1999 TO 2001]"}
```

Unlike regular date queries, which require exact matches or date math applied to field (e.g. `/DAY`), [DateRangeField supports a concise truncated date format](https://cwiki.apache.org/confluence/display/solr/Working+with+Dates):
```
2000-11       – The entire month of November, 2000.
2000-11T13    – Likewise but for an hour of the day (1300 to before 1400, i.e. 1pm to 2pm).
-0009         – The year 10 BC. A 0 in the year position is 0 AD, and is also considered 1 BC. 
[2000-11-01 TO 2014-12-01] – The specified date range at a day resolution.
[2014 TO 2014-12-01]       – From the start of 2014 till the end of the first day of December.
[* TO 2014-12-01]          – From the earliest representable time thru till the end of the day on 2014-12-01.
```

Lastly, at this layer, the intent should be to expose (or avoid concealing) as much solr functionality as possible.  After all, we didn't ask "What's the use case indexed but unstored field_type_X values vs. indexed and stored field_type_X values?"  Individual use cases would exist at higher levels.

**Comment by jcoyne** [comment]
We don't represent leases or embargoes as a range, so I didn't see that as a use case that would benefit.

**Comment by atz** [comment]
Right, we would be able to combine both with a range field and simplify our modeling, terminology and querying.  Since multiple values are supported, we could also have a decent logical representation of multiple periods of visibility ("Each July for the next 10 years"), which would otherwise be unintelligible ("10 Embargoes and 10 Leases with no relationship to each other").
