### ISSUE TITLE
Files from Fedora are buffered, rather than streamed for downloads

### ISSUE THREAD

**Issue by botimer** [samvera/hydra-head#434]
### Descriptive summary

A fix to stream downloads was attempted in #421 but was reverted in #427. It's not clear why looping and doing a `response.stream.write` does not actually stream, but files are most definitely buffered, effectively breaking very large downloads.

### Rationale

Using `self.response_body=` in a controller is the recommended way to handle streaming downloads. The default, implicit `render` in `ActionController` detects this body and considers the render to be performed, sending headers and beginning the stream immediately. If the body responds to `#each`, it will be streamed.

### Expected behavior

Files from Fedora should be streamed, rather than buffered.

### Steps to reproduce the behavior

1. Add a large file (say, 2GB or larger) to a FileSet
1. Download the file as part of a generic_work
1. Watch memory consumption grow to match the file size

### Related work

#421 
#427

**Comment by jcoyne** [comment]
@botimer what version of hydra-head are you seeing this in?

**Comment by botimer** [comment]
10.5.0; also present in 11.0.0.rc1.

**Comment by jcoyne** [comment]
The revision was not present in 10.5.0, so if you saw this problem there, #427 is not the issue.

**Comment by botimer** [comment]
Ahh, sure. Sorry for confusion. Either way, the fix attempted in #421 is not present in 10.5.0 or master (11.0.0.rc1). Downloads are buffered into memory as fast as Fedora can stream -- I'm looking at 100GB+ resident in production right now as I deploy the 10.5.0 patch in [our hotfix branch](https://github.com/mlibrary/hydra-head/commit/032f2cdad4283cd4c8ebba2f966c5c1ce3b21eb9).

**Comment by cjcolvar** [comment]
When this gets fixed I think it should go in a 10.5.1 release ASAP as well as master (11.0.0.rc1).  @botimer @jcoyne Does that sound good to you?  I'll draw up plans for a 11.0.0 release as well.

**Comment by botimer** [comment]
That sounds good to me. Should we make a 10.5 or 10.x release branch from the v10.5.0 tag, or is there some further point along master with changes that should be released in 10.5.1?

FWIW, the hotfix mentioned above is in production and happily streams a 56GB file from a ~250MB resident puma worker. It still grew some after starting the stream, but stabilized quickly.
