### ISSUE TITLE
BLACKLIGHT_VERSION not used by travis

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hydra-head#439]
### Descriptive summary

The `BLACKLIGHT_VERSION` environment variable isn't being respected by travis in the bundle install.

### Rationale

The `BLACKLIGHT_VERSION` environment variable allows us to test with a specific version of blacklight to ensure compatibility with specific versions especially older versions.

### Expected behavior

Travis bundle installs the version of blacklight specified by `BLACKLIGHT_VERSION`.

### Actual behavior

Travis bundle installs the latest blacklight version that matches the gemspec restrictions.

**Comment by jcoyne** [comment]
We used to have https://github.com/samvera/hydra-head/commit/5991392d27f8a3765fab54061f3661cc1817f383#diff-93cb22574ece26fa7717ab22d8332c69R6, and I think that's been removed.

**Comment by jrgriffiniii** [comment]
Travis CI is no longer used.
