### ISSUE TITLE
Update the supported rails and ruby versions

### ISSUE THREAD

**Issue by cjcolvar** [samvera/hydra-head#441]
### Descriptive summary

Find the minimum version of ruby and rails that hydra-head can support and update gemspec files appropriately.  This should be done before releasing 11.0.0.

### Rationale

hydra-head, hydra-core, and hydra-access-controls all claim to work with ruby 1.9.3 but I kind of doubt this is the case.  Any version of ruby prior to 2.3 is end of life so hydra-head may want to declare a minimum of ruby 2.3.

Similarly hydra-head claims rails '>= 3.2.6' where hydra-core and hydra-access-controls both require activesupport greater than 4 and less than 6.  Any version of rails prior to 4.2 is end of life.

**Comment by no-reply** [comment]
It looks to me like actual present support might be

  Ruby 2.2+
  Rails 5.0+

With a small effort, I can't get a working build on Ruby 2.1 or Rails 4.x.

I'd propose to update documentation, release one last 10.x without changing declared support, and then limit to what we actually want to support, e.g. Ruby 2.3+, Rails 5.0.7+.

https://travis-ci.org/samvera/hydra-head/builds/433714388?utm_source=github_status&utm_medium=notification

**Comment by cjcolvar** [comment]
That sounds good to me.  Do you mind making a ticket for any work that you're not planning on doing now?

**Comment by jrgriffiniii** [comment]
This is deprecated by https://github.com/samvera/maintenance/issues/164 and https://github.com/samvera/maintenance/issues/165
