### ISSUE TITLE
Wiki lessons, broken link

### ISSUE THREAD

**Issue by nomoregrapes** [samvera/hydra-head#446]
On the [Lesson gated discovery filter search results based on permissions](https://github.com/samvera/hydra-head/wiki/Lesson---gated-discovery---filter-search-results-based-on-permissions) the text `Now we will uncomment one of the lines that we commented out in Lesson: Turn Off Access Controls.` contains a broken link.

The correct link is
[Lesson make blacklight return search results (step 1)](https://github.com/samvera/hydra/wiki/Lesson---make-blacklight-return-search-results#step-1-explicitly-disable-the-code-that-enforces-access-controls-in-blacklights-catalogcontroller)

**Comment by RudyOnRails** [comment]
Good :eyes: - would you like to submit a PR for this or shall I?

**Comment by nomoregrapes** [comment]
Please go ahead.
I don't have a clone of the wiki. I might do that if my work calms down.

**Comment by RudyOnRails** [comment]
Ok, I swapped them out. Look [better](https://github.com/samvera/hydra-head/wiki/Lesson---gated-discovery---filter-search-results-based-on-permissions#step-enable-gated-discovery-in-catalogcontroller)?
