### ISSUE TITLE
Cannot load rails console due to ActiveSupport::Concern::MultipleIncludedBlocks error

### ISSUE THREAD

**Issue by bunderwood** [samvera/hydra-head#468]
In v10.6.0, the rails console fails to load although the rails server loads ok.
I was in the middle of developing a new instance of Hyrax 2.3.3 with Hydra-head v10.5.1 when, during a rebuild, everything was bumped to v10.6.0 -- this is when I started getting the error.

```
/<my_home_dir>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.6/lib/active_support/concern.rb:126:in `included': Cannot define multiple 'included' blocks for a Concern (ActiveSupport::Concern::MultipleIncludedBlocks)
from /<my_home_dir>/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/hydra-access-controls-10.6.0/app/models/concerns/hydra/access_controls/embargoable.rb:7:in `<module:Embargoable>'
```

### Steps to reproduce the behavior

1. `$ rails console -e production`

### Failed steps toward attempted resolution
1. If the "included" block is removed or commented out from `embargoable.rb`, the ActiveSupport error merely trips on the next files called. Of course this is not a feasible solution because there are multiple files being loaded and these files obviously need the dependencies they are calling.
2. Reinstalled & re-configured entire app from hosted repo: 
`rails _5.1.6_ new my_app -m https://raw.githubusercontent.com/samvera/hyrax/v2.3.3/template.rb`
3. Not yet attempted, extreme last-ditch effort: remove all gems and `bundle install` again ?

### I am a new Ruby developer...
And can't figure out how to trace this error upstream. Where are the other "included" blocks being called? All of the .rb files that live inside of the relevant <hyrax/hydra gems>/app/models/concerns only seem to be extending the ActiveSupport module once, and only call the "included" block once. I'm stuck.

**Comment by jcoyne** [comment]
I bet this is because you are running the production environment with a bundle that includes spring. The fix is to:`bundle install —without development test`

**Comment by bunderwood** [comment]
> I bet this is because you are running the production environment with a bundle that includes spring. The fix is to: `bundle install --without development test`

Waah. Tried it, still no work-ey. Thanks @jcoyne .

**Comment by cjcolvar** [comment]
I have a stock Hyrax 2.3.3 app and was not able to reproduce this behavior.  @bunderwood Is there anything special about the hyrax app where you're seeing this happen?

**Comment by bunderwood** [comment]
> Not yet attempted, extreme last-ditch effort: remove all gems and bundle install again ?

I completely reinstalled Ruby 2.5.0 and ran `bundle install` to pull down fresh copies of my gems.
✅ ... and now it works. 

All, please accept my apologies for raising this issue that clearly had nothing to do with this repo. I must have messed up something along the way while in this learning process. Thanks for your help!

**Comment by RudyOnRails** [comment]
You may already know, but if you ever have some byebugs or modified code in gems that you don't care to track down (just in case that was the issue here), you can do a `bundle install --force`. Start it, then go grab a coffee while nokogiri installs.

**Comment by bunderwood** [comment]
Kevin, thanks so much. I did not know that. I suspect that is what the problem is. In fact, it could have even been a problem with how some of the gems were installed. As a totally Ruby noob, I know I did some things as sudo which probably broke permissions along the way. Backing up and re-installing Ruby and all of my gems worked but that was an extreme measure. I'll add this to my tool belt. Thanks again.

________________________________
