### ISSUE TITLE
Drop support for Rails 5.0

### ISSUE THREAD

**Issue by tpendragon** [samvera/hydra-head#481]
Rails version 5.0 is longer receiving regular security patches, as per https://guides.rubyonrails.org/maintenance_policy.html, but is being tested in the build matrix.

@cjcolvar Is there any reason we shouldn't drop that from the build?

**Comment by cjcolvar** [comment]
It's still getting severe security patches so I'd rather leave it in for now until it drops off entirely.  I assume that will happen in a couple months or so.
