### ISSUE TITLE
Support Ruby 3.0 releases

### ISSUE THREAD

**Issue by jrgriffiniii** [samvera/hydra-head#544]
Derived from samvera/maintenance#77

**Comment by jrgriffiniii** [comment]
This is blocked by https://github.com/samvera/active_fedora/issues/1470, as release 13.2.7 is locked to Ruby releases `~> 2.4`

**Comment by jrgriffiniii** [comment]
Upgrading `ldp` is still blocking this. I am advancing these upgrades with the commits tracked on this branch: https://github.com/samvera/ldp/compare/allow-ruby-3.0?expand=1

**Comment by cjcolvar** [comment]
Draft PR https://github.com/samvera/hydra-head/pull/553 waiting on ActiveFedora support  https://github.com/samvera/active_fedora/pull/1489
